version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aquabuilder
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]

